#Server Configuration
server:
  port: 8080

#H2 Database
spring:
  datasource:
    url: "jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS transportation"
    driverClassName: org.h2.Driver
    username: "sa"
    password: "sa"
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
          ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
  banner:
    location: "classpath:banner.txt"
